language: ruby
bundler_args: --without undev
env:
  global:
    - DB=postgresql
    - TRAVIS=true
  matrix:
    - TASK=spinach
    - TASK="spec -I contexts -p"
    - TASK="spec -I controllers -p"
    - TASK="spec -I factories -p"
    - TASK="spec -I features -p"
    - TASK="spec -I fixtures -p"
    - TASK="spec -I helpers -p"
    - TASK="spec -I javascripts -p"
    - TASK="spec -I lib -p"
    - TASK="spec -I mailers -p"
    - TASK="spec -I models -p"
    - TASK="spec -I observers -p"
    - TASK="spec -I requests -p"
    - TASK="spec -I routing -p"
    - TASK="spec -I services -p"
    - TASK="spec -I support -p"
    - TASK="spec -I tasks -p"
    - TASK="spec -I workers -p"
    - TASK=jasmine:ci
before_install:
  - sudo apt-get install libicu-dev -y
  - gem install charlock_holmes -v="0.6.9"
rvm:
  - 2.0.0
services:
  - postgresql
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/gitlab.yml.example config/gitlab.yml"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:seed_fu"
script: "bundle exec rake $TASK --trace"
