language: ruby
bundler_args: --without undev
env:
  - TASK=spinach DB=postgresql TRAVIS=true
  - TASK=spec DB=postgresql TRAVIS=true
  - TASK=jasmine:ci DB=postgresql TRAVIS=true
before_install:
  - sudo apt-get install libicu-dev -y
  - gem install charlock_holmes -v="0.6.9"
rvm:
  - 2.0.0
services:
  - postgresql
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/gitlab.yml.example config/gitlab.yml"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:seed_fu"
script: "bundle exec rake $TASK --trace"
