---
send_daily_digests:
  description: 'Send daily digests'
  queue: mail_notifications
  class: 'Summaries::DailyWorker'
  every:
    - '1h'
    - :first_in: '5m'

send_weekly_digests:
  description: 'Send weekly digests'
  queue: mail_notifications
  class: 'Summaries::WeeklyWorker'
  every:
    - '1h'
    - :first_in: '10m'

send_monthly_digests:
  description: 'Send monthly digests'
  queue: mail_notifications
  class: 'Summaries::MonthlyWorker'
  every:
    - '1h'
    - :first_in: '15m'
